/**
 * @file autonomous_temporary.c
 *
 * @brief This source file was generated by cantools version 40.2.2 Wed May 21 14:10:59 2025.
 *
 * @copyright Copyright (c) 2018-2019 Erik Moqvist
 *
 * @par License
 * The MIT License (MIT)
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

#include <string.h>

#include "autonomous_temporary.h"

static inline uint8_t pack_left_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_left_shift_u16(
    uint16_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_right_shift_u16(
    uint16_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value >> shift) & mask);
}

static inline uint16_t unpack_left_shift_u16(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint16_t)((uint16_t)(value & mask) << shift);
}

static inline uint8_t unpack_right_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value & mask) >> shift);
}

static inline uint16_t unpack_right_shift_u16(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint16_t)((uint16_t)(value & mask) >> shift);
}

int autonomous_temporary_acu_ms_pack(
    uint8_t *dst_p,
    const struct autonomous_temporary_acu_ms_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u8(src_p->mission_select, 0u, 0xffu);

    return (8);
}

int autonomous_temporary_acu_ms_unpack(
    struct autonomous_temporary_acu_ms_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->mission_select = unpack_right_shift_u8(src_p[0], 0u, 0xffu);

    return (0);
}

int autonomous_temporary_acu_ms_init(struct autonomous_temporary_acu_ms_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct autonomous_temporary_acu_ms_t));

    return 0;
}

uint8_t autonomous_temporary_acu_ms_mission_select_encode(double value)
{
    return (uint8_t)(value);
}

double autonomous_temporary_acu_ms_mission_select_decode(uint8_t value)
{
    return ((double)value);
}

bool autonomous_temporary_acu_ms_mission_select_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

int autonomous_temporary_jetson_ms_pack(
    uint8_t *dst_p,
    const struct autonomous_temporary_jetson_ms_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u8(src_p->mission_select, 0u, 0xffu);

    return (8);
}

int autonomous_temporary_jetson_ms_unpack(
    struct autonomous_temporary_jetson_ms_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->mission_select = unpack_right_shift_u8(src_p[0], 0u, 0xffu);

    return (0);
}

int autonomous_temporary_jetson_ms_init(struct autonomous_temporary_jetson_ms_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct autonomous_temporary_jetson_ms_t));

    return 0;
}

uint8_t autonomous_temporary_jetson_ms_mission_select_encode(double value)
{
    return (uint8_t)(value);
}

double autonomous_temporary_jetson_ms_mission_select_decode(uint8_t value)
{
    return ((double)value);
}

bool autonomous_temporary_jetson_ms_mission_select_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

int autonomous_temporary_vcu_rpm_pack(
    uint8_t *dst_p,
    const struct autonomous_temporary_vcu_rpm_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u16(src_p->rpm, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(src_p->rpm, 8u, 0xffu);

    return (8);
}

int autonomous_temporary_vcu_rpm_unpack(
    struct autonomous_temporary_vcu_rpm_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->rpm = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    dst_p->rpm |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);

    return (0);
}

int autonomous_temporary_vcu_rpm_init(struct autonomous_temporary_vcu_rpm_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct autonomous_temporary_vcu_rpm_t));

    return 0;
}

uint16_t autonomous_temporary_vcu_rpm_rpm_encode(double value)
{
    return (uint16_t)(value);
}

double autonomous_temporary_vcu_rpm_rpm_decode(uint16_t value)
{
    return ((double)value);
}

bool autonomous_temporary_vcu_rpm_rpm_is_in_range(uint16_t value)
{
    return (value <= 100u);
}

int autonomous_temporary_target_rpm_pack(
    uint8_t *dst_p,
    const struct autonomous_temporary_target_rpm_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u16(src_p->rpm, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(src_p->rpm, 8u, 0xffu);

    return (8);
}

int autonomous_temporary_target_rpm_unpack(
    struct autonomous_temporary_target_rpm_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->rpm = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    dst_p->rpm |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);

    return (0);
}

int autonomous_temporary_target_rpm_init(struct autonomous_temporary_target_rpm_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct autonomous_temporary_target_rpm_t));

    return 0;
}

uint16_t autonomous_temporary_target_rpm_rpm_encode(double value)
{
    return (uint16_t)(value);
}

double autonomous_temporary_target_rpm_rpm_decode(uint16_t value)
{
    return ((double)value);
}

bool autonomous_temporary_target_rpm_rpm_is_in_range(uint16_t value)
{
    return (value <= 100u);
}

int autonomous_temporary_acu_ign_pack(
    uint8_t *dst_p,
    const struct autonomous_temporary_acu_ign_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u8(src_p->ign, 0u, 0xffu);
    dst_p[1] |= pack_left_shift_u8(src_p->ign_switch, 0u, 0xffu);

    return (8);
}

int autonomous_temporary_acu_ign_unpack(
    struct autonomous_temporary_acu_ign_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->ign = unpack_right_shift_u8(src_p[0], 0u, 0xffu);
    dst_p->ign_switch = unpack_right_shift_u8(src_p[1], 0u, 0xffu);

    return (0);
}

int autonomous_temporary_acu_ign_init(struct autonomous_temporary_acu_ign_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct autonomous_temporary_acu_ign_t));

    return 0;
}

uint8_t autonomous_temporary_acu_ign_ign_encode(double value)
{
    return (uint8_t)(value);
}

double autonomous_temporary_acu_ign_ign_decode(uint8_t value)
{
    return ((double)value);
}

bool autonomous_temporary_acu_ign_ign_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t autonomous_temporary_acu_ign_ign_switch_encode(double value)
{
    return (uint8_t)(value);
}

double autonomous_temporary_acu_ign_ign_switch_decode(uint8_t value)
{
    return ((double)value);
}

bool autonomous_temporary_acu_ign_ign_switch_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

int autonomous_temporary_rd_jetson_pack(
    uint8_t *dst_p,
    const struct autonomous_temporary_rd_jetson_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u8(src_p->rd, 0u, 0xffu);

    return (8);
}

int autonomous_temporary_rd_jetson_unpack(
    struct autonomous_temporary_rd_jetson_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->rd = unpack_right_shift_u8(src_p[0], 0u, 0xffu);

    return (0);
}

int autonomous_temporary_rd_jetson_init(struct autonomous_temporary_rd_jetson_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct autonomous_temporary_rd_jetson_t));

    return 0;
}

uint8_t autonomous_temporary_rd_jetson_rd_encode(double value)
{
    return (uint8_t)(value);
}

double autonomous_temporary_rd_jetson_rd_decode(uint8_t value)
{
    return ((double)value);
}

bool autonomous_temporary_rd_jetson_rd_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

int autonomous_temporary_as_state_pack(
    uint8_t *dst_p,
    const struct autonomous_temporary_as_state_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u8(src_p->state, 0u, 0xffu);

    return (8);
}

int autonomous_temporary_as_state_unpack(
    struct autonomous_temporary_as_state_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->state = unpack_right_shift_u8(src_p[0], 0u, 0xffu);

    return (0);
}

int autonomous_temporary_as_state_init(struct autonomous_temporary_as_state_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct autonomous_temporary_as_state_t));

    return 0;
}

uint8_t autonomous_temporary_as_state_state_encode(double value)
{
    return (uint8_t)(value);
}

double autonomous_temporary_as_state_state_decode(uint8_t value)
{
    return ((double)value);
}

bool autonomous_temporary_as_state_state_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

int autonomous_temporary_vcu_hv_pack(
    uint8_t *dst_p,
    const struct autonomous_temporary_vcu_hv_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u8(src_p->hv, 0u, 0xffu);

    return (8);
}

int autonomous_temporary_vcu_hv_unpack(
    struct autonomous_temporary_vcu_hv_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->hv = unpack_right_shift_u8(src_p[0], 0u, 0xffu);

    return (0);
}

int autonomous_temporary_vcu_hv_init(struct autonomous_temporary_vcu_hv_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct autonomous_temporary_vcu_hv_t));

    return 0;
}

uint8_t autonomous_temporary_vcu_hv_hv_encode(double value)
{
    return (uint8_t)(value);
}

double autonomous_temporary_vcu_hv_hv_decode(uint8_t value)
{
    return ((double)value);
}

bool autonomous_temporary_vcu_hv_hv_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

int autonomous_temporary_res_pack(
    uint8_t *dst_p,
    const struct autonomous_temporary_res_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u8(src_p->signal, 0u, 0xffu);

    return (8);
}

int autonomous_temporary_res_unpack(
    struct autonomous_temporary_res_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->signal = unpack_right_shift_u8(src_p[0], 0u, 0xffu);

    return (0);
}

int autonomous_temporary_res_init(struct autonomous_temporary_res_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct autonomous_temporary_res_t));

    return 0;
}

uint8_t autonomous_temporary_res_signal_encode(double value)
{
    return (uint8_t)(value);
}

double autonomous_temporary_res_signal_decode(uint8_t value)
{
    return ((double)value);
}

bool autonomous_temporary_res_signal_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}
